//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_invoice()
        {
            this.quantity_of_purchased = new HashSet<quantity_of_purchased>();
        }
    
        public int no { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> item_code { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual warehouse warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quantity_of_purchased> quantity_of_purchased { get; set; }
    }
}
