//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_invoice
    {
        public int no { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> item_code { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> prod_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
