//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantity_at_warehouse
    {
        public int item_code { get; set; }
        public int warehouse_id { get; set; }
        public int quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
